exit unless node.platform == 'freebsd'

template '/etc/hosts' do
  source 'templates/hosts.erb'
  owner 'root'
  group node.dig('wheel', 'group')
  mode '0644'
end

# ⚠⚠ **`/etc/resolv.conf` を template で直接置いてはいけない（pooza/chubo2#75）。**
# FreeBSD の `/etc/resolv.conf` は resolvconf(8) の生成物で、DHCP のインタフェースでは
# dhclient が起動・renew のたびに resolvconf 経由で書き戻す。直接置くと **itamae は毎回
# 「変更した」と報告するのに、次の再起動で消える**。成功扱いのままドリフトが見えない、という
# 一番たちの悪い形になる。
#
# 実測（2026-08-15）: Linode の 4 台（shallu / zugoga / gomander / deas）は resolv.conf が
# 「# Generated by resolvconf」＋ Linode のリゾルバで、レシピの成果は残っていなかった。
# 一方 pirazal / pirazis（静的 IP）には 2024-11 の `namseerver` 誤字がそのまま残っていた。
# **どちらも「レシピが管理しているつもり」だけがあって、実機は別物**だった。
#
# 意図は resolvconf.conf 側で伝える。`name_servers` は生成される resolv.conf の先頭に入るので
# DHCP が配るものより優先される（resolver(5) は先頭 3 つまでしか見ないので実質こちらだけが
# 使われ、DHCP 由来のものは後ろに残って保険になる）。
execute 'resolvconf -u' do
  action :nothing
end

# ⚠ **リゾルバは node yaml で宣言させる。**LAN の機体（dev24-26）は社内名を引くために
# LAN の DNS を見ており、ここを固定値の 1.1.1.1 にすると **社内名前解決が壊れる**。
# 既定値は platform yaml の `resolver.name_servers`。
template '/etc/resolvconf.conf' do
  source 'templates/resolvconf.conf.erb'
  owner 'root'
  group node.dig('wheel', 'group')
  mode '0644'
  variables(
    name_servers: node.dig('resolver', 'name_servers') || [],
    search_domains: node.dig('resolver', 'search_domains') || [],
  )
  notifies :run, 'execute[resolvconf -u]'
end
